### ISSUE TITLE
Error #11321 "gatsby-remark-related-posts" threw an error while running the onCreateNode lifecycle

### ISSUE THREAD

**Issue by wingchin** [sititou70/gatsby-remark-related-posts#3]
Every time I use `gatsby build` I will get the following errors:

```
ERROR #11321  PLUGIN

"gatsby-remark-related-posts" threw an error while running the onCreateNode lifecycle:

invalid id

  89 |     var vector = bow_vectors.get(id);
  90 |     if (vector === undefined)
> 91 |         throw new Error('invalid id');
     |               ^
  92 |     var vector_node = {
  93 |         id: id,
  94 |         vector: vector,

File: node_modules/gatsby-remark-related-posts/gatsby-node.js:91:15



  Error: invalid id
  
  - gatsby-node.js:91 getRelatedPosts
    [naamloos]/[gatsby-remark-related-posts]/gatsby-node.js:91:15
  
  - gatsby-node.js:242 Object.exports.onCreateNode
    [naamloos]/[gatsby-remark-related-posts]/gatsby-node.js:242:25
  
  - api-runner-node.js:350 runAPI
    [naamloos]/[gatsby]/src/utils/api-runner-node.js:350:22
  
  - api-runner-node.js:460 Promise.catch.decorateEvent.pluginName
    [naamloos]/[gatsby]/src/utils/api-runner-node.js:460:17
  
  - debuggability.js:384 Promise._execute
    [naamloos]/[bluebird]/js/release/debuggability.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [naamloos]/[bluebird]/js/release/promise.js:518:18
  
  - promise.js:103 new Promise
    [naamloos]/[bluebird]/js/release/promise.js:103:10
  
  - api-runner-node.js:459 
    [naamloos]/[gatsby]/src/utils/api-runner-node.js:459:14
  
  - util.js:16 tryCatcher
    [naamloos]/[bluebird]/js/release/util.js:16:23
  
  - reduce.js:166 Object.gotValue
    [naamloos]/[bluebird]/js/release/reduce.js:166:18
  
  - reduce.js:155 Object.gotAccum
    [naamloos]/[bluebird]/js/release/reduce.js:155:25
  
  - util.js:16 Object.tryCatcher
    [naamloos]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:547 Promise._settlePromiseFromHandler
    [naamloos]/[bluebird]/js/release/promise.js:547:31
  
  - promise.js:604 Promise._settlePromise
    [naamloos]/[bluebird]/js/release/promise.js:604:18
  
  - promise.js:649 Promise._settlePromise0
    [naamloos]/[bluebird]/js/release/promise.js:649:10
  
  - promise.js:729 Promise._settlePromises
    [naamloos]/[bluebird]/js/release/promise.js:729:18
  

not finished source and transform nodes - 0.183s
```

There seem to be no problems in development.
I'm using Gatsby CLI version: 2.12.99, Gatsby version: 2.24.58, Gatsby-remark-related-posts: 0.0.7

**Comment by wingchin** [comment]
The problem seems to be related to the posts_dir. I have the following code in gatsby-config.js, which throws out the error:

```
    {
      resolve: `gatsby-remark-related-posts`,
      options: {
        posts_dir: `${__dirname}/content/posts/`
      },
    },
```

If I do not define any options or I change the directory to `${__dirname}/content/`, then the build would be successful, but adding any subdirectory would cause the error. Even moving the directory out of "content" folder would not help. Strangely, as mentioned before, the problem isn't there in development environment.

**Comment by sititou70** [comment]
Thank you for using this plugin!

> Every time I use gatsby build I will get the following errors:

OK, I tried to reproduce your error on [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog).

First, I installed my plugin to the latest gatsby-starter-blog, and the plugin did works well. This is the gatsby-starter-blog repository I installed my plugin:
https://github.com/sititou70/gatsby-remark-related-posts-example

Please clone this repository, `npm i && npm start` and exec [this query](http://localhost:8000/___graphql?query=query%20%7B%0A%20%20allMarkdownRemark%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20relatedFileAbsolutePaths%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=undefined).
Can you see the post id and related post list?

Next, I intentionally changed the value of `post_dir` in `gatsby-config.js` to the wrong one, such as `${__dirname}/content/blo`. Then I got the same error as yours. Thus, I suspect that you may mistake the `post_dir` value.

**Comment by wingchin** [comment]
Thank you for paying attention to my issue. 

The minimal reproduction I created earlier can be found here: https://github.com/wingchin/gatsby-related-posts-helloworld
I'll test your repository now.

**Comment by wingchin** [comment]
I cloned your repository and executed the query in development environment. I can see all the post ids and related post lists in GraphiQL. `gatsby build` also works.

Then I simulated the situation from my minimal reproduction by creating another instance of source nodes by duplicating the blog2 folder:

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog`,
        name: `blog`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/blog2`,
        name: `blog2`,
      },
    },
```
Afterwarrds, `gatsby clean && gatsby build` would immediately cause the error. Check out this commit: https://github.com/wingchin/gatsby-remark-related-posts-example/commit/2da74570a84d80c3ae18c305ec91a0be193197ed

**Comment by sititou70** [comment]
I had misunderstood the meaning of your problem. Your error occurred because the plugin did not support multiple file sources, and this is not your fault.

gatsby-remark-related-posts@0.0.8 is supporting multiple file sources. And I created [the pull request](https://github.com/wingchin/gatsby-related-posts-helloworld/pull/1) on your helloworld repository. The result of my plugin is what you want?

**Comment by wingchin** [comment]
Yes exactly! Thank you!
