### ISSUE TITLE
Once I got the file location of the md file how should I be getting its title and other Frontmatter?

### ISSUE THREAD

**Issue by billyperalta89** [sititou70/gatsby-remark-related-posts#4]
Sorry I am new to Gatsby, If someone can create a sample showing how to show the properties of the relatedFileAbsolutePaths that would be great.

**Comment by sititou70** [comment]
here!
https://github.com/sititou70/gatsby-remark-related-posts-example

**Comment by canibanoglu** [comment]
Ummm, how does that repository answer the question? There's absolutely no usage of the plugin that I can see.

**Comment by sititou70** [comment]
Sorry for the lack of sample code.

Today, I added a component that displays related posts to [the repository](https://github.com/sititou70/gatsby-remark-related-posts-example). I hope that those codes will be useful to you.

**Comment by gokaykucuk** [comment]
Thank you!

**Comment by canibanoglu** [comment]
Thanks a lot for the fast reply and update! <3 

I am curious what you'd think of returning the related post data directly from the plugin instead of doing the filtering and selecting on the client.

**Comment by sititou70** [comment]
yeah, I also want to return markdownRemark object directly. But if I create a field that has markdownRemark object in markdownRemark object, `gatsby build` will hang up.

Perhaps gatsby is having an infinite loop when generating the graphql schema, but I don't know the exact cause ...

If I come up with a good implementation, I'll update the features.

**Comment by dkmooers** [comment]
For any Gatsby newbies like me, took me a minute to figure out that I also had to look at gatsby-node.js in the example repo above, in the createPage function for blog posts, and add to `context`: `relatedFileAbsolutePaths: post.fields.relatedFileAbsolutePaths`, to make they graphql query work in the blog-post.js template.
