### ISSUE TITLE
your thoughts on WordPress YARPP (related post)

### ISSUE THREAD

**Issue by Hari-Bonda** [sititou70/gatsby-remark-related-posts#7]
Hello, i am not here to criticise but i want to know the potential of the algorithm used in this repo. I have read [your article](https://sititou70.github.io/Gatsby%E8%A3%BD%E3%83%96%E3%83%AD%E3%82%B0%E3%81%A7%E8%87%AA%E7%84%B6%E8%A8%80%E8%AA%9E%E5%87%A6%E7%90%86%E3%81%97%E3%81%A6%E9%96%A2%E9%80%A3%E8%A8%98%E4%BA%8B%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B/) (google translated version) the approach looks interesting, do you think it works better than YARPP (i don't know I am not so experienced in this) we are looking to use WordPress YARPP since we are already using WP as the source to generate Gatsby pages. could you go through this and share your thoughts https://github.com/matepaiva/yarpp-wpgraphql _they are working on it for the last 10years_ 

https://wordpress.org/plugins/yet-another-related-posts-plugin/

https://videos.files.wordpress.com/0n2TSzkb/09_h264_4160k_2997p_hd.mp4

**Comment by sititou70** [comment]
Hi, I got to know YARPP for the first time with this question.

YARPP uses the document "search" technique, while my plugin uses the document "classification" technique. I thought that the algorithms used by both plugins were standard in their respective fields.

I haven't compared the results of both, so I don't know which method is better. It's easy to try each plugin and decide which one is better.
